### ISSUE TITLE
master not discovered yet

### ISSUE THREAD

**Issue by asdf2014** [hmdmph/helm-charts#11]
```java
[WARN ][o.e.c.c.ClusterFormationFailureHelper] [Cima Scanaiol] master not discovered yet, this node has not previously joined a bootstrapped (v4+) cluster, 
and this node must discover master-eligible nodes [2] to bootstrap a cluster: have discovered 
[{Hoher Eichham}{JNAIYWyES_eJYPJ1yv3ufA}{02IXtb5USmGs6Gu7x3gEFQ}{10.244.3.66}{10.244.3.66:4300}{http_address=10.244.3.66:4200}, 
{Monte Pettini}{sSOjUD51RsyOVmGOdgBwTg}{uCVyIISKT7mlmJPqLdP4hA}{10.244.1.75}{10.244.1.75:4300}{http_address=10.244.1.75:4200}]; 
discovery will continue using [127.0.0.1:4301, 127.0.0.1:4302, 127.0.0.1:4303, 127.0.0.1:4304, 127.0.0.1:4305, 10.111.118.74:4300] 
from hosts providers and [{Cima Scanaiol}{K1azywQzTLqTHDr2542brg}{kLI185A7QWqWVkHSPG0_2A}{10.244.5.46}{10.244.5.46:4300}{http_address=10.244.5.46:4200}] 
from last-known cluster state; node term 0, last-accepted version 0 in term 0
```

```bash
$ helm version
version.BuildInfo{Version:"v3.2.3", GitCommit:"8f832046e258e2cb800894579b1b3b50c2d83492", GitTreeState:"clean", GoVersion:"go1.13.12"}

$  kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by asdf2014** [comment]
@hmdmph PTAL

**Comment by hmdmph** [comment]
@asdf2014 Let me check the issue, Thanks 👍

**Comment by hmdmph** [comment]
Hi @asdf2014,

I have installed fresh Redis cluster and tried to the labelling found one thing, except that it is working without any issue. 
Installed the redis-ha cluster using the following command

`helm upgrade --install  redis-ha  bitnami/redis --namespace=redis --set master.persistence.enabled=false,slave.persistence.enabled=false,sentinel.enabled=true,sentinel.usePassword=false`

by default 
  - `sentinel.enabled` is set to false ( we have to enable this since its the one use to determine `master/ slave`
  -  `sentinel.usePassword` is set to true ( I've disabled this, as of now chart does not support this, will release next one with the support of password)
  
### Successful redis-ha cluster returned following

![Screen Shot 2020-07-12 at 3 38 42 PM](https://user-images.githubusercontent.com/2019997/87241450-cf746f00-c455-11ea-842b-0e340d590161.png)
![Screen Shot 2020-07-12 at 3 42 47 PM](https://user-images.githubusercontent.com/2019997/87241501-63463b00-c456-11ea-9b39-dc9a81b2526c.png)
![Screen Shot 2020-07-12 at 3 38 42 PM](https://user-images.githubusercontent.com/2019997/87241502-64776800-c456-11ea-88e7-74f7d66bd65f.png)

### Correct labelling is working as in snaps

![Screen Shot 2020-07-12 at 3 44 33 PM](https://user-images.githubusercontent.com/2019997/87241529-aaccc700-c456-11ea-9277-ef1679703fcf.png)
![Screen Shot 2020-07-12 at 3 44 23 PM](https://user-images.githubusercontent.com/2019997/87241530-ac968a80-c456-11ea-992c-1aefe34c53f3.png)

If you see in the redis-pod-labeller deployment you should see correct values your provided/overrided in `values.yaml` when you install it.

![Screen Shot 2020-07-12 at 3 46 20 PM](https://user-images.githubusercontent.com/2019997/87241582-3e9e9300-c457-11ea-82ad-715a3467dfe6.png)

`--svc-selector=release=redis-ha` -   **release=redis-ha** is the service selecter
`--redis-cluster-name=mymaster` -  **mymaster** is the default sentinal cluster name ( unless u have given something else)
`--redis-headless-svc-name=redis-ha-headless` - **redis-ha-headless** headless service name

So if you have given proper values for three above three labellings should work. All others are quite common, still u can have different values.

**Comment by hmdmph** [comment]
Closing the issue, hope @asdf2014 resolved the case.
